In [1]:
from sklearn.datasets import load_iris

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
iris=load_iris()

In [4]:
pd.DataFrame(iris.data)

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x,y=load_iris(return_X_y=True)

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.1,random_state=21)

In [8]:
from sklearn.naive_bayes import GaussianNB

In [9]:
gs=GaussianNB()

In [10]:
gs

GaussianNB()

In [11]:
gs.fit(x_train,y_train)

GaussianNB()

In [12]:
gs

GaussianNB()

In [13]:
y_pred=gs.predict(x_test)

In [14]:
y_pred

array([1, 0, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 2, 0])

In [15]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix,consensus_score

In [16]:
print(confusion_matrix(y_pred,y_test))

[[7 0 0]
 [0 5 0]
 [0 0 3]]


In [17]:
print(accuracy_score(y_pred,y_test))

1.0


In [18]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00         5
           2       1.00      1.00      1.00         3

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15



In [51]:
from sklearn.datasets import load_svmlight_files

In [54]:
dataset=load_svmlight_files()

TypeError: load_svmlight_files() missing 1 required positional argument: 'files'

In [53]:
dataset

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [47]:
pd.DataFrame(dataset.data,columns=[dataset.feature_names])

alcohol malic_acid   ash alcalinity_of_ash magnesium total_phenols  \
0     14.23       1.71  2.43              15.6     127.0          2.80   
1     13.20       1.78  2.14              11.2     100.0          2.65   
2     13.16       2.36  2.67              18.6     101.0          2.80   
3     14.37       1.95  2.50              16.8     113.0          3.85   
4     13.24       2.59  2.87              21.0     118.0          2.80   
..      ...        ...   ...               ...       ...           ...   
173   13.71       5.65  2.45              20.5      95.0          1.68   
174   13.40       3.91  2.48              23.0     102.0          1.80   
175   13.27       4.28  2.26              20.0     120.0          1.59   
176   13.17       2.59  2.37              20.0     120.0          1.65   
177   14.13       4.10  2.74              24.5      96.0          2.05   

    flavanoids nonflavanoid_phenols proanthocyanins color_intensity   hue  \
0         3.06                 0.28            2.29            5.64  1.04   
1         2.76                 0.26            1.28            4.38  1.05   
2         3.24                 0.30            2.81            5.68  1.03   
3         3.49                 0.24            2.18            7.80  0.86   
4         2.69                 0.39            1.82            4.32  1.04   
..         ...                  ...             ...             ...   ...   
173       0.61                 0.52            1.06            7.70  0.64   
174       0.75                 0.43            1.41            7.30  0.70   
175       0.69                 0.43            1.35           10.20  0.59   
176       0.68                 0.53            1.46            9.30  0.60   
177       0.76                 0.56            1.35            9.20  0.61   

    od280/od315_of_diluted_wines proline  
0                           3.92  1065.0  
1                           3.40  1050.0  
2                           3.17  1185.0  
3                           3.45  1480.0  
4                           2.93   735.0  
..                           ...     ...  
173                         1.74   740.0  
174                         1.56   750.0  
175                         1.56   835.0  
176                         1.62   840.0  
177                         1.60   560.0  

[178 rows x 13 columns]

In [50]:
pd.DataFrame(dataset.target,columns=[dataset.target_names])

ValueError: Shape of passed values is (178, 1), indices imply (178, 3)

In [31]:
x,y=load_diabetes(return_X_y=True)

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [62]:

data={"acsTransID": "340be29-4c52-47f8-85f8-6e0a53d7106a", "frmTranId": "082f1b3c-38b6-4b65-9b69-eb882d7ef0f9", "acctNumber": "6385672000000255", "error": "", "prediction_anomaly": "0", "prediction_score": "0.4931859868768151"}
 
 
 
 


In [63]:
for i in data.keys():
    print(i)

acsTransID
frmTranId
acctNumber
error
prediction_anomaly
prediction_score
